# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_github_packages: RGLab/ImmuneSpaceR
script: travis_wait 40 Rscript script.R
